apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- crd/bases/gco.galos.one_gitcommits.yaml
- crd/bases/gco.galos.one_pullrequests.yaml
- crd/bases/gco.galos.one_gitchangeoperators.yaml
- rbac/rbac.yaml
- manager/manager.yaml